Add model
microhass/blog-app pull request #1
Opened 2023-09-20 04:14 UTC by hassanShakur

In this branch, I implemented the following requirements:

- Create a new app. Give it a meaningful name.
- Build your project schema.
    - Create and run the necessary migration files.
    - Table and column names should match the ERD diagram.
        - note: photo for users table should be a link to an image
    - Foreign keys should be included.
        - Pay attention that in `posts` table the column holding the foreign key to the `users` table should be named `author_id`
    - All columns that are foreign keys should have a corresponding index.
- Be sure to reference the from the sneak peek if you have any questions about table or column names or data relationships.

2023-09-20 04:31 UTC, Davidosky007 reviewed
Hi @hassanShakur 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a linter configuration, Kindly [check the config](https://github.com/microverseinc/linters-config/tree/master/ror)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-09-20 18:10 UTC, KDlamini requested changes
### Hi @hassanShakur 🙋‍♀️,  

Great work so far! 💯 
You have done a great job creating a data model for the blog app. 🎊 🥳 
There are some issues that you still need to work on to improve your project according to the requirements. You are almost there! 💪🏾 



## Highlights 🌞

✔️  Good PR title and description
✔️  Well-documented and professional README 
✔️  `User`, `Post`, `Comment`, and `Like` migrations files are present
✔️  Foreign keys and indexes are included

## Required Changes ♻️

**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-20 18:10 UTC, KDlamini commented on README.md
> +
[OPTIONAL] to optimize your README, I think it would be best if you removed any additional information.

1. Kindly remove the additional text on the `Show your support` section:

![image](https://github.com/microhass/blog-app/assets/38088818/e189c784-c3ef-4075-b0e1-0b10b1c782f7)

2. Kindly remove the additional back to top link on the `Acknowledgments` section:

![image](https://github.com/microhass/blog-app/assets/38088818/792ba656-acb1-4d27-8f52-4cc9765434bc)

2023-09-20 18:10 UTC, KDlamini commented on config.ru
On the `config/database.yml` kindly make sure that your application is configured to use PostgreSQL. Currently your application is configured to use `sqlite3`.

The default setting should look like this:

##### config/database.yml
```ruby

default: &default
adapter: postgresql
encoding: unicode

```

Your configuration:

![image](https://github.com/microhass/blog-app/assets/38088818/29d6b50c-3219-4c95-8254-c39ca4604178)


* Remeber to also add the `pg` gem `gem 'pg', '~> 1.2'` in the Gemfile.

2023-09-20 18:10 UTC, KDlamini commented on db/migrate/20230919190352_add_user_ref_to_posts.rb
> +end
Kindly make sure that the post table references the `author`  as per project requirements. The `posts` table the column holding the foreign key to the `users` table should be named `author_id`.

![image](https://github.com/microhass/blog-app/assets/38088818/abd6ef30-68e7-4fc4-9db6-a10e8078d99b)

The Posts migration file should add foreign key in a similar way like to this `t.references :author, foreign_key: { to_table: 'users' }` in order to create `author_id` and a corresponding index.

Currently your schema has `user_id` instead of `author_id` on the Post table.

![image](https://github.com/microhass/blog-app/assets/38088818/fca7ea3e-2aee-42b5-88f8-b05850eb9d95)

2023-09-20 18:33 UTC, hassanShakur commented on config.ru
@KDlamini, must I regenerate the entire app or making this changes will do the trick?

2023-09-20 21:27 UTC, OyePriscilla approved these changes
Hi @hassanShakur 👏 👏 👏 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Database adapter used Postgresql✔️ 
Created `author_id` and a corresponding index ✔️ 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-21 04:41 UTC, merged

2023-09-22 06:30 UTC, KDlamini commented on config.ru
> @KDlamini, must I regenerate the entire app or making this changes will do the trick?

Hi, apologies for the late reply. Making the changes will do the trick, you do not need to start afresh.