Add forms
microhass/blog-app pull request #7
Opened 2023-09-28 18:54 UTC by hassanShakur

In this branch, I implemented the following requirements:

-  Create a method called `current_user` in your ApplicationController to make current user data available to all controllers.
    -  It will return the first user from the database.
    -  Don't worry about proper authentication at this time. You will add it in the upcoming projects.
- Create forms to perform the following functions:
    - Creates a Post on behalf of the `current_user` (use the method that you created in your ApplicationController).
    - Create a comment on behalf of the `current_user` (use the method that you created in your ApplicationController).
- Allow Users to add likes to Posts.

2023-09-28 20:03 UTC, Shedrack-Sunday requested changes
Hello @hassanShakur         👋 

# CHANGES REQUIRED ♻️

Impressive work on the project so far👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️   
- Nice work with the Rails   features ✔️ 
- Nice use of Controller  parameters✔️ 

# Required Changes  🌵  

- [x] You've done well, However, kindly follow the suggestion on the right query pattern properly so your impressive work will have a better implementation 👍 


_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-09-28 20:03 UTC, Shedrack-Sunday commented on config/routes.rb
> +    resources :posts, only: [:index, :show, :new, :create] do
-[ ] From your Routes, i can't find the `posts#new` and `posts#create` paths. The create should have a `POST` method

### Your view
![image](https://github.com/microhass/blog-app/assets/50990925/afe1b740-8467-411e-a6f0-36e79a8f6888)

2023-09-28 20:03 UTC, Shedrack-Sunday commented on config/routes.rb
> +      resources :comments, only: [:new, :create]
-  [ ] Just like for the post, you need endpoints for your comments. Though implemneted here, i can't find thein the routes log out output.

### Your view:
![image](https://github.com/microhass/blog-app/assets/50990925/5604af1b-a24e-4625-ad01-616f6a1a21ad)

### Sample of expected:
```
   POST   /posts/:post_id/comments(.:format)     comments#create
 GET   /posts/:post_id/comments/new(.:format)     comments#new
```

2023-09-28 20:03 UTC, Shedrack-Sunday commented on app/controllers/users_controller.rb
> +
- [ ] After adding two users and running your app, it turns out their not been added to the database as `ids` were not even assigned to them. Kindly review this and make sure added users are been added

### View:
![image](https://github.com/microhass/blog-app/assets/50990925/1d82d527-6498-485c-8a7e-2c65a4bab8f7)

2023-09-29 05:31 UTC, hassanShakur commented on config/routes.rb
> +      resources :comments, only: [:new, :create]
Hey @Shedrack-Sunday, could the issue be from your end? I have rechecked my routes and the post actions for posts, comments, and likes are present.

![image](https://github.com/microhass/blog-app/assets/119076463/d205818b-2357-4cdb-9f79-f3d1f24286f0)

I would appreciate your feedback if I am doing something wrong.

2023-09-29 07:39 UTC, Ibizugbe approved these changes
Hi @hassanShakur 👋🏼👋🏼👋🏼, 

![approved](https://github.com/microhass/blog-app/assets/64643995/c66135a1-b3a5-472b-b433-72a8c8134b52)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] The routes have been properly updated👍🏼.
- [x] List of users are properly rendered👍🏼.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-29 07:44 UTC, merged